exclude: (.github|.gradle|.idea|.jenkins|config|data|docker-compose|docs|frontend|gradle|iris-client|config|templates|open-compliance-*)/.*
default_install_hook_types:
- pre-commit
- commit-msg
default_language_version:
  python: python3.12
repos:
#- repo: https://github.com/PyCQA/docformatter/
#  rev: v1.7.5
#  hooks:
#  - id: docformatter
#    args:
#    - --wrap-descriptions=120
#    - --wrap-summaries=120
#    - --close-quotes-on-newline
#    - --pre-summary-newline
#    - --in-place
#  - id: docformatter-venv
#    name: docformatter-venv
#    description: 'Formats docstrings to follow PEP 257. Uses python3 -m venv.'
#    entry: docformatter
#    args: [-i]
#    language: python
#    types: [python]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.13.0
  hooks:
  - id: mypy
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
  - id: nbstripout
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.6.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: [--verbose, feat, fix, perf, refactor, style, test, docs, build, ci, chore]
- repo: https://github.com/PyCQA/bandit
  rev: 1.8.0
  hooks:
  - id: bandit
    args: [-c, pyproject.toml]
    additional_dependencies: ['bandit[toml]']
- repo: https://github.com/PyCQA/pylint
  rev: v3.3.2
  hooks:
  - id: pylint
    args:
    - --disable=import-error,import-outside-toplevel,missing-module-docstring,missing-class-docstring,too-few-public-methods,missing-function-docstring
    - --ignore-paths=^app/migrations/.*|tests/app/.*$
    - --max-line-length=120
    - --good-names=a,b,e,i,j,k,l,r,x,y,z,u,v,w,p,q,n,ch,fp,wb,ws
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.3
  hooks:
  - id: ruff
    exclude: lgca/utils/hexagon.py
    # Respect `exclude` and `extend-exclude` settings.
    args:
    - --fix
    - --line-length=120
    - --output-format=github
    - --target-version=py312
    - --ignore=F401
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-yaml
    args:
    - --allow-multiple-documents
    exclude: mkdocs.yaml
  - id: check-json
  - id: end-of-file-fixer
    exclude: html
  - id: trailing-whitespace
    exclude: html
  - id: check-ast
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: pretty-format-json
    exclude_types: [jupyter]
    args:
    - --autofix
    - --indent=2
  - id: name-tests-test
    args:
    - --pytest-test-first
  - id: fix-byte-order-marker
  - id: debug-statements
  - id: trailing-whitespace
    args:
    - --markdown-linebreak-ext=md
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
    args:
    - --line-length=120
- repo: https://github.com/myint/autoflake.git
  rev: v2.3.1
  hooks:
  - id: autoflake
    args:
    - --in-place
    - --remove-all-unused-imports
    - --remove-unused-variable
    - --expand-star-imports
    - --ignore-init-module-imports
- repo: https://github.com/pycqa/flake8
  rev: 7.1.1        # pick a git hash / tag to point to
  hooks:
  - id: flake8
    exclude: lgca/utils/hexagon.py
    args:
    - --max-line-length=120
    - --max-complexity=10
    - --ignore=A003,W503,F401
    additional_dependencies:
    - flake8-blind-except
    - flake8-builtins
- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.43.0
  hooks:
  - id: markdownlint
  - id: markdownlint-fix
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-use-type-annotations
